"""Stable persistence contracts used by the application services.

Backends deliberately expose domain operations instead of database details, so
the API, CLI and web UI remain independent from the storage technology.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional, Protocol

from infrastructure.storage.schemas import BenchmarkResult, ExperimentRecord, LoadTestingResult


class ExperimentRepository(Protocol):
    def save(self, record: ExperimentRecord) -> None: ...
    def get(self, experiment_id: str) -> Optional[ExperimentRecord]: ...
    def delete(self, experiment_id: str) -> bool: ...
    def list_all(self) -> list[ExperimentRecord]: ...


class BenchmarkResultRepository(Protocol):
    def append(self, result: BenchmarkResult, overwrite: bool = False) -> Path: ...
    def load(self, model: str) -> list[BenchmarkResult]: ...
    def delete_latest(self, model: str, benchmark: str, timestamp: str | None = None) -> bool: ...
    def latest_by_benchmark(self, model: str) -> dict[str, BenchmarkResult]: ...
    def list_models(self) -> list[str]: ...
    def dashboard_matrix(self) -> dict: ...


class LoadTestingRepository(Protocol):
    def append(self, result: LoadTestingResult) -> Path: ...
    def latest(self) -> list[LoadTestingResult]: ...
    def delete(self, model: str, provider: str, concurrent_users: int, timestamp: str) -> bool: ...
