import React, { useEffect, useMemo, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { api } from "../api/client.js";

function PrettyData({ value, indent = 0 }) {
  if (value === null || value === undefined || value === "") return <span className="empty-cell">-</span>;
  if (typeof value !== "object") return <span>{typeof value === "number" ? value.toLocaleString() : String(value)}</span>;
  const entries = Object.entries(value).filter(([, item]) => item !== null && item !== undefined && item !== "" && (typeof item !== "object" || Object.keys(item).length));
  return <div>{entries.map(([key, item]) => <div key={`${indent}-${key}`} className="data-line" style={{ paddingLeft: `${indent * 2}ch` }}><strong>{key}:</strong>{typeof item === "object" && item !== null ? <PrettyData value={item} indent={indent + 1} /> : <span> {String(item)}</span>}</div>)}</div>;
}
const pretty = (value) => <div className="metadata-block"><PrettyData value={value || {}} /></div>;
const Prompt = ({ result }) => { const text = result.prompt || result.input || ""; const shown = text.length > 100 ? `${text.slice(0, 100)}...` : text; return <details className="prompt-block"><summary><strong>{result.input_filename || "Prompt"}:</strong> {shown}</summary>{text.length > 100 && <div className="prompt-full">{text}</div>}</details>; };
const MetricTable = ({ value }) => <table className="metric-card-table"><thead><tr><th>Key</th><th>Value</th></tr></thead><tbody>{Object.entries(value || {}).filter(([, v]) => v !== null && v !== undefined && v !== "").map(([key, item]) => <tr key={key}><td><strong>{key}</strong></td><td>{typeof item === "object" ? <PrettyData value={item} /> : String(item)}</td></tr>)}</tbody></table>;
const Card = ({ title, children, onDelete }) => <div className="result-card"><div className="result-card-header"><h3>{title}</h3><button className="danger" onClick={onDelete}>Delete</button></div>{children}</div>;
export default function ModelResults() {
  const { model } = useParams(); const [searchParams] = useSearchParams(); const fromLoadTesting = searchParams.get("from") === "load_testing"; const [benchmarks, setBenchmarks] = useState(null); const [loads, setLoads] = useState(null); const [error, setError] = useState(null);
  const refresh = () => Promise.all([api.getModelResults(model).catch(() => ({ results: [] })), api.getLoadTestingResults()]).then(([b, s]) => { setBenchmarks(b.results || []); setLoads((s.results || []).filter((r) => r.model === model)); }).catch((e) => setError(e.message));
  useEffect(() => { refresh(); }, [model]);
  const groups = useMemo(() => { const map = new Map(); [...(benchmarks || []).map((r) => ({ type: "benchmarks", provider: r.metadata.provider, config: r.metadata.metadata, result: r })), ...(loads || []).map((r) => ({ type: "loads", provider: r.provider, config: r.metadata, result: r }))].forEach((x) => { const key = `${x.provider}\0${JSON.stringify(x.config || {})}`; if (!map.has(key)) map.set(key, { provider: x.provider, config: x.config || {}, benchmarks: [], loads: [] }); map.get(key)[x.type].push(x.result); }); return [...map.values()]; }, [benchmarks, loads]);
  const remove = async (message, action) => { if (window.confirm(message)) { await action(); refresh(); } };
  if (error) return <div className="panel error-text">{error}</div>; if (!benchmarks || !loads) return <div className="panel">Loading...</div>;
  const renderGroups = (type) => { const byProvider = new Map(); groups.filter((g) => g[type].length).forEach((g) => { if (!byProvider.has(g.provider)) byProvider.set(g.provider, []); byProvider.get(g.provider).push(g); }); return [...byProvider].map(([provider, configs]) => <details open className="provider-section" key={`${type}-${provider}`}><summary><h3>Provider: {provider}</h3></summary>{configs.map((g) => <section className="model-group" key={`${type}-${provider}-${JSON.stringify(g.config)}`}><div className="panel configuration"><div className="result-card-header"><strong>Configuration</strong><button className="danger" onClick={() => remove("Delete all results for this configuration?", () => Promise.all([...g.benchmarks.map((r) => api.deleteDetailedResult(model, r.metadata.benchmark, r.metadata.timestamp)), ...g.loads.map((r) => api.deleteLoadTestingResult(r))]))}>Delete configuration</button></div>{pretty(g.config)}{type === "loads" && <Prompt result={g.loads[0]} />}<div className="result-cards">{g[type].map((r) => <Card key={`${type}-${r.metadata.timestamp}`} title={type === "benchmarks" ? `Benchmark: ${r.metadata.benchmark}` : `Load testing: ${r.concurrent_users} concurrent users`} onDelete={() => remove(type === "benchmarks" ? "Delete this benchmark result?" : "Delete this load-test result?", () => type === "benchmarks" ? api.deleteDetailedResult(model, r.metadata.benchmark, r.metadata.timestamp) : api.deleteLoadTestingResult(r))}><MetricTable value={r.metrics} /></Card>)}</div></div></section>)}</details>); };
  return <div><Link className="model-link" to={fromLoadTesting ? "/load_testing" : "/"}>&larr; Back</Link><h1>{model}</h1><details open={!fromLoadTesting} className="results-section"><summary><h2>Benchmark results</h2></summary>{renderGroups("benchmarks")}</details><details open={fromLoadTesting} className="results-section"><summary><h2>Load Testing results</h2></summary>{renderGroups("loads")}</details>{!groups.length && <div className="panel">No results for this model.</div>}</div>;
}
